-- TaskMD Production Data Seed
-- Generated by export_data.sh
-- This file contains the current production data from the database
--
-- Usage:
--   psql -d taskmd -f production_seed.sql
--

-- Disable triggers during data load
SET session_replication_role = replica;

BEGIN;

-- Export timestamp: 2025-12-28 07:24:20 UTC

-- Users
TRUNCATE users CASCADE;
INSERT INTO users (id, email, name, avatar_url, password_hash, oidc_provider, oidc_subject, preferences, created_at, updated_at, last_login_at) VALUES ('system','system@taskmd.local','System',NULL,NULL,NULL,NULL,'{}'::jsonb,'2025-12-28 00:24:41.803673+00'::timestamp,'2025-12-28 00:24:41.803673+00'::timestamp,NULL);

-- Projects
TRUNCATE projects CASCADE;
INSERT INTO projects (id, name, description, visibility, settings, created_at, updated_at, archived_at) VALUES ('proj-1766881508-s3ujc5','プロジェクト','説明です','private','{}'::jsonb,'2025-12-28 00:25:08.426055+00'::timestamp,'2025-12-28 00:25:08.426055+00'::timestamp,NULL);

-- Tasks
TRUNCATE tasks CASCADE;
INSERT INTO tasks (id, project_id, parent_id, title, status, priority, assignees, labels, start_date, due_date, markdown_body, extra_meta, created_at, updated_at, completed_at, archived_at, created_by, updated_by) VALUES ('T-1766881526042','proj-1766881508-s3ujc5',NULL,'タスクA','review','P0','{佐藤}'::text[],'{}'::text[],'2025-12-26'::date,'2025-12-29'::date,'## T-1766881526042: タスクA

```yaml
id: T-1766881526042
status: review
priority: P0
assignees: ["佐藤"]
labels: []
start_date: 2025-12-26
due_date: 2025-12-29
extra_meta: {"actual_start_date": "2025-12-27", "actual_end_date": "2025-12-30", "summary": "残はレビューです"}
```

## 背景

背景です

<details>
  <summary>空行あり(クリックしてください)</summary>

  ### Heading
  1. Foo
  2. Bar
     * Baz
     * Qux
      
  ### Some Code
  ```js
  function logSomething(something) {
    console.log(''Something'', something);
  }
  ```
</details>','{"summary": "残はレビューです", "actual_end_date": "2025-12-30", "actual_start_date": "2025-12-27"}'::jsonb,'2025-12-28 00:25:26.05115+00'::timestamp,'2025-12-28 01:40:25.686715+00'::timestamp,NULL,NULL,'system','system');
INSERT INTO tasks (id, project_id, parent_id, title, status, priority, assignees, labels, start_date, due_date, markdown_body, extra_meta, created_at, updated_at, completed_at, archived_at, created_by, updated_by) VALUES ('T-1766883560644','proj-1766881508-s3ujc5',NULL,'タスクB','in_progress','P2','{佐藤}'::text[],'{}'::text[],'2026-01-02'::date,'2025-12-31'::date,'## T-1766883560644: タスクB

```yaml
id: T-1766883560644
status: in_progress
priority: P2
assignees: ["佐藤"]
labels: []
extra_meta: {"summary": "ひとこと整形で変更しました", "actual_start_date": "2025-12-28", "actual_end_date": "2025-12-30"}
start_date: 2026-01-02
due_date: 2025-12-31
```

## はいけい

ひとこと

## T-1766883560644: タスクB
> ひとこと整形
- **ステータス**: 未着手
- **優先度**: 余裕があれば
---

## T-1766881526042: タスク
- **ステータス**: 未着手
- **優先度**: 緊急
- **開始日**: 2025/12/26
- **期限**: 2025/12/29
- **担当者**: 担当者','{"summary": "ひとこと整形で変更しました", "actual_end_date": "2025-12-30", "actual_start_date": "2025-12-28"}'::jsonb,'2025-12-28 00:59:20.650269+00'::timestamp,'2025-12-28 04:11:51.975326+00'::timestamp,NULL,NULL,'system','system');
INSERT INTO tasks (id, project_id, parent_id, title, status, priority, assignees, labels, start_date, due_date, markdown_body, extra_meta, created_at, updated_at, completed_at, archived_at, created_by, updated_by) VALUES ('T-1766894052755','proj-1766881508-s3ujc5',NULL,'タスクC','open','P4','{aaa}'::text[],'{}'::text[],'2026-01-08'::date,'2026-01-11'::date,'## T-1766894052755: タスクC

```yaml
id: T-1766894052755
status: open
priority: P4
assignees: ["aaa"]
labels: []
start_date: 2026-01-08
due_date: 2026-01-11
extra_meta: {"summary": "いつかやるタスクdesu"}
```

いつかやる
','{"summary": "いつかやるタスクdesu"}'::jsonb,'2025-12-28 03:54:12.765247+00'::timestamp,'2025-12-28 04:40:50.155778+00'::timestamp,NULL,NULL,'system','system');
INSERT INTO tasks (id, project_id, parent_id, title, status, priority, assignees, labels, start_date, due_date, markdown_body, extra_meta, created_at, updated_at, completed_at, archived_at, created_by, updated_by) VALUES ('T-1766905607558','proj-1766881508-s3ujc5','T-1766881526042','子タスクA','open','P2','{}'::text[],'{}'::text[],NULL,NULL,'## T-1766905607558: 子タスクA

```yaml
id: T-1766905607558
status: open
priority: P2
parent_id: T-1766881526042
assignees: []
labels: []
```

あああ
','{}'::jsonb,'2025-12-28 07:06:47.562917+00'::timestamp,'2025-12-28 07:09:48.817458+00'::timestamp,NULL,NULL,'system','system');

-- Saved Views
TRUNCATE saved_views CASCADE;
INSERT INTO saved_views (id, project_id, owner_user_id, name, description, scope, raw_query, normalized_query, presentation, use_count, last_used_at, created_at, updated_at) VALUES ('proj-1766881508-s3ujc5-view-recent-done','proj-1766881508-s3ujc5',NULL,'Recently Completed','Tasks completed in the last 7 days','shared','status:done','[status:done]','{"limit": 100}'::jsonb,34,'2025-12-28 07:20:42.525462+00'::timestamp,'2025-12-28 00:25:08.426055+00'::timestamp,'2025-12-28 07:20:42.525462+00'::timestamp);
INSERT INTO saved_views (id, project_id, owner_user_id, name, description, scope, raw_query, normalized_query, presentation, use_count, last_used_at, created_at, updated_at) VALUES ('proj-1766881508-s3ujc5-view-p0-p1-open','proj-1766881508-s3ujc5',NULL,'P0/P1 Open','High priority open tasks','shared','status:(open in_progress) priority:(P2 P1 P0)','[status:[open in_progress] priority:[P2 P1 P0]]','{"limit": 100}'::jsonb,47,'2025-12-28 07:20:43.035958+00'::timestamp,'2025-12-28 00:25:08.426055+00'::timestamp,'2025-12-28 07:20:43.035958+00'::timestamp);
INSERT INTO saved_views (id, project_id, owner_user_id, name, description, scope, raw_query, normalized_query, presentation, use_count, last_used_at, created_at, updated_at) VALUES ('proj-1766881508-s3ujc5-view-my-work-today','proj-1766881508-s3ujc5',NULL,'My Work (Today)','Tasks assigned to me due today','shared','start_date:<=today','[start_date:2025-12-28]','{"limit": 100}'::jsonb,63,'2025-12-28 07:20:43.408899+00'::timestamp,'2025-12-28 00:25:08.426055+00'::timestamp,'2025-12-28 07:20:43.408899+00'::timestamp);
INSERT INTO saved_views (id, project_id, owner_user_id, name, description, scope, raw_query, normalized_query, presentation, use_count, last_used_at, created_at, updated_at) VALUES ('proj-1766881508-s3ujc5-view-my-work-week','proj-1766881508-s3ujc5',NULL,'My Work (This Week)','Tasks assigned to me due this week','shared','start_date:<=next_sunday','[start_date:2026-01-04]','{"limit": 100}'::jsonb,69,'2025-12-28 07:20:43.803553+00'::timestamp,'2025-12-28 00:25:08.426055+00'::timestamp,'2025-12-28 07:20:43.803553+00'::timestamp);
INSERT INTO saved_views (id, project_id, owner_user_id, name, description, scope, raw_query, normalized_query, presentation, use_count, last_used_at, created_at, updated_at) VALUES ('proj-1766881508-s3ujc5-view-blocked','proj-1766881508-s3ujc5',NULL,'Blocked','Tasks that are currently blocked','shared','status:blocked','[status:blocked]','{"limit": 100}'::jsonb,57,'2025-12-28 07:20:44.577391+00'::timestamp,'2025-12-28 00:25:08.426055+00'::timestamp,'2025-12-28 07:20:44.577391+00'::timestamp);
INSERT INTO saved_views (id, project_id, owner_user_id, name, description, scope, raw_query, normalized_query, presentation, use_count, last_used_at, created_at, updated_at) VALUES ('proj-1766881508-s3ujc5-view-all-open','proj-1766881508-s3ujc5',NULL,'All','All','shared','','[]','{"limit": 100}'::jsonb,67,'2025-12-28 07:20:45.014817+00'::timestamp,'2025-12-28 00:25:08.426055+00'::timestamp,'2025-12-28 07:20:45.014817+00'::timestamp);


COMMIT;

-- Re-enable triggers
SET session_replication_role = DEFAULT;

-- Update sequences to max values
SELECT setval('audit_log_id_seq', COALESCE((SELECT MAX(id) FROM audit_log), 1));
SELECT setval('task_revisions_rev_id_seq', COALESCE((SELECT MAX(rev_id) FROM task_revisions), 1));

