#!/bin/bash
# Export current database data as migration seed file
# This script dumps all data from the current database and creates a seed file

set -e  # Exit on error

# Load environment variables from .env if it exists
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [ -f "$SCRIPT_DIR/../.env" ]; then
    set -a
    source "$SCRIPT_DIR/../.env"
    set +a
fi

# Configuration
DB_HOST="${DB_HOST:-localhost}"
DB_PORT="${DB_PORT:-5432}"
DB_NAME="${DB_NAME:-taskmd}"
DB_USER="${DB_USER:-postgres}"
DB_PASSWORD="${DB_PASSWORD:-}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Helper functions
info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

error() {
    echo -e "${RED}[ERROR]${NC} $1"
    exit 1
}

# Parse arguments
OUTPUT_FILE="$SCRIPT_DIR/seeds/production_seed.sql"
TIMESTAMP=$(date +%Y%m%d_%H%M%S)

while [[ $# -gt 0 ]]; do
    case $1 in
        --output|-o)
            OUTPUT_FILE="$2"
            shift 2
            ;;
        --timestamp)
            OUTPUT_FILE="$SCRIPT_DIR/seeds/backup_${TIMESTAMP}.sql"
            shift
            ;;
        --help|-h)
            echo "Usage: $0 [OPTIONS]"
            echo ""
            echo "Options:"
            echo "  --output, -o FILE    Output file path (default: db/seeds/production_seed.sql)"
            echo "  --timestamp          Add timestamp to filename"
            echo "  --help, -h           Show this help message"
            echo ""
            echo "Environment variables:"
            echo "  DB_HOST      Database host (default: localhost)"
            echo "  DB_PORT      Database port (default: 5432)"
            echo "  DB_NAME      Database name (default: taskmd)"
            echo "  DB_USER      Database user (default: postgres)"
            echo "  DB_PASSWORD  Database password"
            exit 0
            ;;
        *)
            error "Unknown option: $1"
            ;;
    esac
done

# Build psql command
PSQL_CMD="psql -h $DB_HOST -p $DB_PORT -U $DB_USER"

if [ -n "$DB_PASSWORD" ]; then
    export PGPASSWORD="$DB_PASSWORD"
fi

info "TaskMD Data Export"
info "=================="
info "Host: $DB_HOST:$DB_PORT"
info "Database: $DB_NAME"
info "User: $DB_USER"
info "Output: $OUTPUT_FILE"
echo ""

# Check PostgreSQL connection
info "Checking PostgreSQL connection..."
if ! $PSQL_CMD -d $DB_NAME -c '\q' 2>/dev/null; then
    error "Cannot connect to PostgreSQL database '$DB_NAME'. Please check your connection settings."
fi
info "✓ Connected to PostgreSQL"

# Create output directory if it doesn't exist
mkdir -p "$(dirname "$OUTPUT_FILE")"

# Start creating the SQL file
info "Exporting data..."

cat > "$OUTPUT_FILE" << 'EOF'
-- TaskMD Production Data Seed
-- Generated by export_data.sh
-- This file contains the current production data from the database
--
-- Usage:
--   psql -d taskmd -f production_seed.sql
--

-- Disable triggers during data load
SET session_replication_role = replica;

BEGIN;

EOF

# Add timestamp
echo "-- Export timestamp: $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Export data from each table in the correct order (respecting foreign keys)

# 1. Users (no dependencies)
info "  → Exporting users..."
echo "-- Users" >> "$OUTPUT_FILE"
echo "TRUNCATE users CASCADE;" >> "$OUTPUT_FILE"
$PSQL_CMD -d $DB_NAME -t -A -F',' -c "
SELECT 'INSERT INTO users (id, email, name, avatar_url, password_hash, oidc_provider, oidc_subject, preferences, created_at, updated_at, last_login_at) VALUES (' ||
       quote_literal(id) || ',' ||
       quote_literal(email) || ',' ||
       quote_literal(name) || ',' ||
       COALESCE(quote_literal(avatar_url), 'NULL') || ',' ||
       COALESCE(quote_literal(password_hash), 'NULL') || ',' ||
       COALESCE(quote_literal(oidc_provider), 'NULL') || ',' ||
       COALESCE(quote_literal(oidc_subject), 'NULL') || ',' ||
       quote_literal(preferences::text) || '::jsonb,' ||
       quote_literal(created_at::text) || '::timestamp,' ||
       quote_literal(updated_at::text) || '::timestamp,' ||
       COALESCE(quote_literal(last_login_at::text) || '::timestamp', 'NULL') || ');'
FROM users ORDER BY created_at;
" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# 2. Projects (no dependencies except users which is optional)
info "  → Exporting projects..."
echo "-- Projects" >> "$OUTPUT_FILE"
echo "TRUNCATE projects CASCADE;" >> "$OUTPUT_FILE"
$PSQL_CMD -d $DB_NAME -t -A -F',' -c "
SELECT 'INSERT INTO projects (id, name, description, visibility, settings, created_at, updated_at, archived_at) VALUES (' ||
       quote_literal(id) || ',' ||
       quote_literal(name) || ',' ||
       COALESCE(quote_literal(description), 'NULL') || ',' ||
       quote_literal(visibility) || ',' ||
       quote_literal(settings::text) || '::jsonb,' ||
       quote_literal(created_at::text) || '::timestamp,' ||
       quote_literal(updated_at::text) || '::timestamp,' ||
       COALESCE(quote_literal(archived_at::text) || '::timestamp', 'NULL') || ');'
FROM projects WHERE archived_at IS NULL ORDER BY created_at;
" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# 3. Tasks (depends on projects)
info "  → Exporting tasks..."
echo "-- Tasks" >> "$OUTPUT_FILE"
echo "TRUNCATE tasks CASCADE;" >> "$OUTPUT_FILE"
$PSQL_CMD -d $DB_NAME -t -A -F',' -c "
SELECT 'INSERT INTO tasks (id, project_id, parent_id, title, status, priority, assignees, labels, start_date, due_date, markdown_body, extra_meta, created_at, updated_at, completed_at, archived_at, created_by, updated_by) VALUES (' ||
       quote_literal(id) || ',' ||
       quote_literal(project_id) || ',' ||
       COALESCE(quote_literal(parent_id), 'NULL') || ',' ||
       quote_literal(title) || ',' ||
       quote_literal(status) || ',' ||
       quote_literal(priority) || ',' ||
       quote_literal(assignees::text) || '::text[],' ||
       quote_literal(labels::text) || '::text[],' ||
       COALESCE(quote_literal(start_date::text) || '::date', 'NULL') || ',' ||
       COALESCE(quote_literal(due_date::text) || '::date', 'NULL') || ',' ||
       quote_literal(markdown_body) || ',' ||
       quote_literal(extra_meta::text) || '::jsonb,' ||
       quote_literal(created_at::text) || '::timestamp,' ||
       quote_literal(updated_at::text) || '::timestamp,' ||
       COALESCE(quote_literal(completed_at::text) || '::timestamp', 'NULL') || ',' ||
       COALESCE(quote_literal(archived_at::text) || '::timestamp', 'NULL') || ',' ||
       COALESCE(quote_literal(created_by), 'NULL') || ',' ||
       COALESCE(quote_literal(updated_by), 'NULL') || ');'
FROM tasks WHERE archived_at IS NULL ORDER BY created_at;
" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# 4. Saved Views (depends on projects)
info "  → Exporting saved views..."
echo "-- Saved Views" >> "$OUTPUT_FILE"
echo "TRUNCATE saved_views CASCADE;" >> "$OUTPUT_FILE"
$PSQL_CMD -d $DB_NAME -t -A -F',' -c "
SELECT 'INSERT INTO saved_views (id, project_id, owner_user_id, name, description, scope, raw_query, normalized_query, presentation, use_count, last_used_at, created_at, updated_at) VALUES (' ||
       quote_literal(id) || ',' ||
       quote_literal(project_id) || ',' ||
       COALESCE(quote_literal(owner_user_id), 'NULL') || ',' ||
       quote_literal(name) || ',' ||
       COALESCE(quote_literal(description), 'NULL') || ',' ||
       quote_literal(scope) || ',' ||
       quote_literal(raw_query) || ',' ||
       quote_literal(normalized_query) || ',' ||
       quote_literal(presentation::text) || '::jsonb,' ||
       use_count || ',' ||
       COALESCE(quote_literal(last_used_at::text) || '::timestamp', 'NULL') || ',' ||
       quote_literal(created_at::text) || '::timestamp,' ||
       quote_literal(updated_at::text) || '::timestamp);'
FROM saved_views ORDER BY created_at;
" >> "$OUTPUT_FILE"
echo "" >> "$OUTPUT_FILE"

# Finish the SQL file
cat >> "$OUTPUT_FILE" << 'EOF'

COMMIT;

-- Re-enable triggers
SET session_replication_role = DEFAULT;

-- Update sequences to max values
SELECT setval('audit_log_id_seq', COALESCE((SELECT MAX(id) FROM audit_log), 1));
SELECT setval('task_revisions_rev_id_seq', COALESCE((SELECT MAX(rev_id) FROM task_revisions), 1));

EOF

info "✓ Data export complete"

# Show statistics
TOTAL_LINES=$(wc -l < "$OUTPUT_FILE")
info ""
info "Summary:"
info "  Output file: $OUTPUT_FILE"
info "  Total lines: $TOTAL_LINES"

# Count records
USER_COUNT=$($PSQL_CMD -d $DB_NAME -t -c "SELECT COUNT(*) FROM users;")
PROJECT_COUNT=$($PSQL_CMD -d $DB_NAME -t -c "SELECT COUNT(*) FROM projects WHERE archived_at IS NULL;")
TASK_COUNT=$($PSQL_CMD -d $DB_NAME -t -c "SELECT COUNT(*) FROM tasks WHERE archived_at IS NULL;")
VIEW_COUNT=$($PSQL_CMD -d $DB_NAME -t -c "SELECT COUNT(*) FROM saved_views;")

info "  Records exported:"
info "    Users: $USER_COUNT"
info "    Projects: $PROJECT_COUNT"
info "    Tasks: $TASK_COUNT"
info "    Saved Views: $VIEW_COUNT"

echo ""
info "You can load this data into a new database using:"
echo "  psql -d <database_name> -f $OUTPUT_FILE"
echo ""

# Clean up
unset PGPASSWORD
